//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fczrk.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public int Id { get; set; }
        public string Position { get; set; }
        public string Company { get; set; }
        public string CompanyUrl { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string Description { get; set; }
        public bool Job { get; set; }
    }
}
