//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fczrk.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int MemberSince { get; set; }
        public string ImageUrl { get; set; }
        public string LinkedInUrl { get; set; }
        public string Description { get; set; }
        public int SectionId { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
    }
}
